# Generated by Django 4.1.7 on 2023-06-05 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VoteEasyApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRegistration',
        ),
    ]
