# Generated by Django 4.1.7 on 2023-06-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoteEasyApp', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='biography',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='candidate',
            name='candidate_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidate',
            name='election_bullets',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='candidate',
            name='image',
            field=models.ImageField(default='images/default.png', upload_to='candidates/'),
        ),
    ]
