# Generated by Django 4.1.7 on 2023-06-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoteEasyApp', '0004_candidate_biography_candidate_candidate_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
