# Generated by Django 4.1.7 on 2023-06-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoteEasyApp', '0006_candidate_voters'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
