# Generated by Django 4.1.7 on 2023-06-13 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VoteEasyApp', '0007_candidate_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VoteEasyApp.candidate')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VoteEasyApp.election')),
            ],
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('candidate', 'election'), name='unique_vote'),
        ),
    ]
